name: build-image

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - name: Build and publish test docker image
      uses: docker/build-push-action@v2
      with:
        context: interop
        file: tests/Dockerfile
        push: true
        tags: ghcr.io/ueno/ghcr:latest
